version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6.0
    container_name: tripledart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7-alpine
    container_name: tripledart-redis
    ports:
      - "6379:6379"
volumes:
  mongo-data:
